//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuMarket_App.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class IlyasovaFriendEntitieser : DbContext
    {
        private static IlyasovaFriendEntitieser _context;
        public IlyasovaFriendEntitieser()
            : base("name=IlyasovaFriendEntitieser")
        {
        }

        public static IlyasovaFriendEntitieser GetContext()
        {
            if (_context == null)
                _context = new IlyasovaFriendEntitieser();

            return _context;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CallMaster> CallMaster { get; set; }
        public virtual DbSet<PaidFor> PaidFor { get; set; }
        public virtual DbSet<Receipt> Receipt { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Users> Users { get; set; }
    }
}
