//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompuMarket_App.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaidFor
    {
        public int PaidId { get; set; }
        public string Adress { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ReceiptId { get; set; }
        public Nullable<long> Number { get; set; }
    
        public virtual Receipt Receipt { get; set; }
        public virtual Users Users { get; set; }

        public PaidFor() { }
        public PaidFor(string adress, long? number, Receipt receipt, Users users)
        {
            this.Adress = adress;      
            this.Number = number;
            this.Receipt = receipt;
            this.Users = users;
        }
    }
}
